### ISSUE TITLE
SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by ghost** [erja/foorumi-api#1]
_Postmanin GET-pyyntö palauttaa kyseisen error-viestin:_

Error: Failed to lookup view "error" in views directory "/home/ubuntu/workspace/foorumi-api/views"
    at EventEmitter.app.render (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/response.js:938:7)
    at /home/ubuntu/workspace/foorumi-api/app.js:63:7
    at Layer.handle_error (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:300:13)
    at /home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:321:12)
    at IncomingMessage.next (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:261:10)
    at res.render.fn (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/response.js:933:25)
    at EventEmitter.app.render (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/application.js:557:14)
    at ServerResponse.res.render (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/response.js:938:7)
    at /home/ubuntu/workspace/foorumi-api/app.js:52:9
    at Layer.handle_error (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:300:13)
    at /home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/ubuntu/workspace/foorumi-api/node_modules/express/lib/router/index.js:321:12)
**Unhandled rejection SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (/home/ubuntu/workspace/foorumi-api/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:60:61)**

_Kun yrittää tarkastella sqlite tietokantaa .read komennolla seuraa:_ 

**Error: incomplete SQL: SQLite format 3 PRIMARY KEY, `title` VARCHAR(255), `content` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `UserId` INTEGER REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, `TopicId` INTEGER REFERENCES `Topics` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)0;tableTopicsTopicsCREATE TABLE `Topics` (`id` INTEGER PRIMARY KEY, `name` VARCHAR(255), `description` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL)6KtableUsersUsersCREATE TABLE `Users` (`id` INTEGER PRIMARY KEY, `username` VARCHAR(255), `password` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DAIME NOT NULL, `MessageId` INTEGER REFERENCES `Messages` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, `UserId` INTEGER REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)**

Onko minulta jäänyt jotain huomaamatta (asennukset tai vastaava) vai onko virhe koodissa?

**Comment by erja** [comment]
Ensimmäiseksi tarkistaisin, että oikeudet kirjoittaa tietokantaan ovat OK?
Toiseksi, eikös tuo tietokanta generoidu automaattisesti sequelize-komennoista? Muistaakseni se generoidaan: tarkista? Jos generoidaan, niin silloin voinee hävittää tiedoston ja katsoa syntyykö uusi kunnollisesti.
